Hw2.1
MihailKulikov/MyHomeworksSem4 pull request #10
Opened 2021-02-23 00:12 UTC by MihailKulikov

2021-02-25 12:08 UTC, yurii-litvinov requested changes
С одной стороны, технично. С другой, не очень аккуратно. Так что предлагаю всё-таки немного стайлгайд пофиксить

2021-02-25 12:08 UTC, yurii-litvinov commented on sem4/hw2.1/hw2.1/Program.fs
> +        |> List.map(fun x -> if x % 2 = 0 then 1 else 0)
Это что-то вроде `abs(x + 1) % 2` на самом деле. Хотя так тоже ок

2021-02-25 12:08 UTC, yurii-litvinov commented on sem4/hw2.1/hw2.1/Program.fs
> +        |> List.map(fun x -> if x % 2 = 0 then 1 else 0)
И пробел перед `(` принято ставить, это же не скобка, ограничивающая список параметров, как в C#, а скобка вокруг одного параметра.

2021-02-25 12:08 UTC, yurii-litvinov commented on sem4/hw2.1/hw2.1/Program.fs
> +        |> List.filter(fun x -> if x % 2 = 0 then true else false)
`then true else false` ужасно :) И тоже надо пробел

2021-02-25 12:08 UTC, yurii-litvinov commented on sem4/hw2.1/Tests/Tests.fs
> +        | _ -> raise (ArgumentException("Invalid test fixture parameter."))
Кстати, просто функцию пробовали в TestFixture передавать? Может не работать, потому что в F# функции не очень ложатся на .NETовскую модель и по ним генерится что-то странное (из-за каррирования), но тут функция с одним параметром, она может в обычный метод сгенериться

2021-02-25 13:07 UTC, MihailKulikov commented on sem4/hw2.1/hw2.1/Program.fs
> +        |> List.filter(fun x -> if x % 2 = 0 then true else false)
:)

2021-02-25 13:20 UTC, MihailKulikov commented on sem4/hw2.1/Tests/Tests.fs
> +        | _ -> raise (ArgumentException("Invalid test fixture parameter."))
Не смог разобраться, как передавать даже методы в TestFixture, во втором семестре.
Сделал через nameof.

2021-03-01 14:38 UTC, yurii-litvinov approved these changes
Теперь всё отлично. Зачтена

2021-03-01 16:38 UTC, merged